name: proto_book
version: 1.0.0+1
publish_to: none

description: A new Flutter project.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: ^4.6.6
  image_picker: ^1.0.8
  font_awesome_flutter: ^10.7.0
  google_fonts: ^4.0.1
  shared_preferences: ^2.2.3
  webview_flutter: ^4.0.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.6.6
  flutter_local_notifications: ^17.2.0
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  speech_to_text: ^6.5.0
  permission_handler: ^11.3.1
  audioplayers: ^5.2.0
  file_picker: ^5.0.0
  path_provider: ^2.0.15
  camera: ^0.10.5+9
  video_player: ^2.5.5
  geolocator: ^11.1.0
  google_maps_flutter: ^2.5.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/