name: proto_book
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
  get: ^4.6.6
  image_picker: ^1.0.8
  font_awesome_flutter: ^10.7.0
  google_fonts: ^4.0.1

dev_dependencies: 
  flutter_lints: ^2.0.3
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

