// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc6Sj-of32S1XWKcLPJxu5kIpkNW5lufE',
    appId: '1:419220958986:web:ed79869fe906e96e5bd4f3',
    messagingSenderId: '419220958986',
    projectId: 'proto-book',
    authDomain: 'proto-book.firebaseapp.com',
    storageBucket: 'proto-book.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt4G7g28OSRbZhWRGQq3_Q0aDmln-1NOQ',
    appId: '1:419220958986:android:3895ddc048a2cd665bd4f3',
    messagingSenderId: '419220958986',
    projectId: 'proto-book',
    storageBucket: 'proto-book.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwhgc4BPjjDITH4eGPUfqrvXLikZPWTaY',
    appId: '1:419220958986:ios:56e98fa8c470c3525bd4f3',
    messagingSenderId: '419220958986',
    projectId: 'proto-book',
    storageBucket: 'proto-book.appspot.com',
    iosBundleId: 'com.book.protoBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwhgc4BPjjDITH4eGPUfqrvXLikZPWTaY',
    appId: '1:419220958986:ios:56e98fa8c470c3525bd4f3',
    messagingSenderId: '419220958986',
    projectId: 'proto-book',
    storageBucket: 'proto-book.appspot.com',
    iosBundleId: 'com.book.protoBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc6Sj-of32S1XWKcLPJxu5kIpkNW5lufE',
    appId: '1:419220958986:web:681dc16cf4baff725bd4f3',
    messagingSenderId: '419220958986',
    projectId: 'proto-book',
    authDomain: 'proto-book.firebaseapp.com',
    storageBucket: 'proto-book.appspot.com',
  );
}
